export const ACCOUNT_EDIT = 'ACCOUNT_EDIT';
export const ACCOUNT_EDIT_SUCCESS = 'ACCOUNT_EDIT_SUCCESS';
export const ACCOUNT_CHANGE_PASSWORD = 'ACCOUNT_CHANGE_PASSWORD';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';

