export const ON_QUERY = 'ON_QUERY';
export const ON_RESET = 'ON_RESET';
export const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
export const ON_AUTOCOMPLETE_SELECT = 'ON_AUTOCOMPLETE_SELECT';
export const ON_QUERY_SUCCESS = 'ON_QUERY_SUCCESS';