export const STUDENT_INIT_COURSE = 'STUDENT_INIT_COURSE';
export const STUDENT_UPDATE_COURSE = 'STUDENT_UPDATE_COURSE';
export const STUDENT_ADD_COURSE = 'STUDENT_ADD_COURSE';
export const STUDENT_REMOVE_COURSE = 'STUDENT_REMOVE_COURSE';



export const UPDATE_REMARKS_SUCCESS = 'UPDATE_REMARKS_SUCCESS';